package pl.edu.agh.sius.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.0
 * 2015-06-04T15:09:32.523+02:00
 * Generated source version: 3.1.0
 * 
 */
@WebService(targetNamespace = "http://www.agh.edu.pl/sius", name = "WService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WService {

    @WebResult(name = "ResponseUser", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseUser")
    @WebMethod(action = "login")
    public ResponseUser login(
        @WebParam(partName = "UserLogin", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String userLogin,
        @WebParam(partName = "UserPassword", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String userPassword,
        @WebParam(partName = "AuthorizationProvider", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String authorizationProvider
    );

    @WebResult(name = "ResponseOrderDetails", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseOrderDetails")
    @WebMethod(action = "addOrder")
    public ResponseOrderDetails addOrder(
        @WebParam(partName = "OrderDetails", name = "OrderDetails", targetNamespace = "http://www.agh.edu.pl/sius")
        OrderDetails orderDetails,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseUser", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseUser")
    @WebMethod(action = "registerUser")
    public ResponseUser registerUser(
        @WebParam(partName = "User", name = "UserRegister", targetNamespace = "http://www.agh.edu.pl/sius")
        User user,
        @WebParam(partName = "UserPassword", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String userPassword
    );

    @WebResult(name = "ResponseOrderDetails", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseOrderDetails")
    @WebMethod(action = "getOrderDetails")
    public ResponseOrderDetails getOrderDetails(
        @WebParam(partName = "OrderID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String orderID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "removeUserFromGroup")
    public ResponseSimple removeUserFromGroup(
        @WebParam(partName = "GroupID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String groupID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseGroupDetails", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseGroupDetails")
    @WebMethod(action = "getGroupDetails")
    public ResponseGroupDetails getGroupDetails(
        @WebParam(partName = "GroupID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String groupID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "newProductInOrder")
    public ResponseSimple newProductInOrder(
        @WebParam(partName = "Product", name = "Product", targetNamespace = "http://www.agh.edu.pl/sius")
        Product product,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponsePayments", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponsePayments")
    @WebMethod(action = "getUsersPayments")
    public ResponsePayments getUsersPayments(
        @WebParam(partName = "User", name = "LoggedUser", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseGroupDetails", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseGroupDetails")
    @WebMethod(action = "addGroup")
    public ResponseGroupDetails addGroup(
        @WebParam(partName = "Group", name = "Group", targetNamespace = "http://www.agh.edu.pl/sius")
        Group group,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "changeDept")
    public ResponseSimple changeDept(
        @WebParam(partName = "UserID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String userID,
        @WebParam(partName = "NewUserMaxDept", name = "Money", targetNamespace = "http://www.agh.edu.pl/sius")
        java.math.BigDecimal newUserMaxDept,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "logout")
    public ResponseSimple logout(
        @WebParam(partName = "User", name = "UserLogout", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "payMoney")
    public ResponseSimple payMoney(
        @WebParam(partName = "StringID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String stringID,
        @WebParam(partName = "Amount", name = "Money", targetNamespace = "http://www.agh.edu.pl/sius")
        java.math.BigDecimal amount,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponsePayments", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponsePayments")
    @WebMethod(action = "getUserPayments")
    public ResponsePayments getUserPayments(
        @WebParam(partName = "User", name = "UserLogged", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "acceptPayment")
    public ResponseSimple acceptPayment(
        @WebParam(partName = "StringID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String stringID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseGroups", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseGroups")
    @WebMethod(action = "findGroup")
    public ResponseGroups findGroup(
        @WebParam(partName = "GroupNamePattern", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String groupNamePattern,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "updateUser")
    public ResponseSimple updateUser(
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user,
        @WebParam(partName = "UserPassword", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String userPassword
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "joinToProduct")
    public ResponseSimple joinToProduct(
        @WebParam(partName = "StringID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String stringID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseUserDetails", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseUserDetails")
    @WebMethod(action = "getUserDetails")
    public ResponseUserDetails getUserDetails(
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseProducts", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseProducts")
    @WebMethod(action = "getProductsOrderedByUser")
    public ResponseProducts getProductsOrderedByUser(
        @WebParam(partName = "User", name = "UserProducts", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "joinUserToGroup")
    public ResponseSimple joinUserToGroup(
        @WebParam(partName = "GroupID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String groupID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );

    @WebResult(name = "ResponseSimple", targetNamespace = "http://www.agh.edu.pl/sius", partName = "ResponseSimple")
    @WebMethod(action = "closeOrder")
    public ResponseSimple closeOrder(
        @WebParam(partName = "OrderID", name = "String", targetNamespace = "http://www.agh.edu.pl/sius")
        java.lang.String orderID,
        @WebParam(partName = "User", name = "User", targetNamespace = "http://www.agh.edu.pl/sius")
        User user
    );
}
